version: "3.9"

services:
  app:
    build:
      context: .
      target: demo-spring-boot-api-db-simple-development
    environment:
      MAVEN_CONFIG: /root/.m2
      SERVER_PORT: 80
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_PASSWORD: super
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myDatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_PROFILES_ACTIVE: dev # local
    expose:
      - 80
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    ports:
      - 80:80
    tty: true
    volumes:
      - ./:/usr/src/app
      - ${HOME}/.m2/repository:/root/.m2/repository

  playwright:
    image: node:18.15.0
    working_dir: /home/node/app
    environment:
      APP_URL: http://app
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    command: npm run test-e2e
    volumes:
      - ./playwright/:/home/node/app

  postgres:
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      # Uncomment this line to enable persistence
      # - postgres:/var/lib/postgresql/data

# Uncomment these lines to enable persistence
# volumes:
#   postgres:
